on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.17
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test
        run: go test -v
        working-directory: ./src/monkey/lexer
